Add support for multiple input files with --in-place (fix #17)
fmang/opustags pull request #26
Opened 2020-08-23 16:30 UTC by rrthomas

2020-08-23 18:05 UTC, fmang requested changes
Thank you for the pull request! Unfortunately it needs some more working on.

This current implementation breaks `--set-all` for multiple files, because opustags reads its tags from stdin while it is processing the Opus file. To support multiple files, we need to read the tags at once into memory before processing the Opus files. That probably deserves a separate pull request before we can merge this one.

It is also missing test cases in `opustags.t`.

Such a feature raises a few other questions:

1. What to do when the same file is specified twice? I think it is reasonable to edit it twice. That’s what sed does.
2. What to do when one file fails? Shouldn’t we continue?
3. What should be the error code if some files succeed but other fail? Right now opustags returns either 0 or 1, so I guess 1 is better when there is a failure.

2020-08-23 19:05 UTC, rrthomas commented
Thanks very much for your feedback; I didn't expect the PR would land first time! I'll see what I can do and update the PR.

2020-08-23 19:11 UTC, rrthomas commented on README.md
> +      -i, --in-place                overwrite the input file(s)
Done!

2020-08-23 19:13 UTC, rrthomas commented on src/cli.cc
> +	for (const std::string& name : opt.path_in) {
`name` renamed to `path_in`, and `opts.path_in` renamed to `opt.paths_in`.

2020-08-23 19:13 UTC, rrthomas commented on t/cli.cc
> +	if (opt.path_in.front() != "x" || opt.path_out != "y" || !opt.delete_all || opt.overwrite ||
Done!

2020-08-23 19:21 UTC, rrthomas commented on src/cli.cc
> +	for (const std::string& name : opt.path_in) {
Factored `run_single` out.

2020-08-23 20:03 UTC, rrthomas commented on src/opustags.h
> +	std::vector<std::string> path_in;
Done!

2020-08-23 20:04 UTC, rrthomas commented on src/cli.cc
> +	for (const std::string& name : opt.path_in) {
(Done!)

2020-08-23 20:42 UTC, rrthomas commented
> This current implementation breaks `--set-all` for multiple files, because opustags reads its tags from stdin while it is processing the Opus file. To support multiple files, we need to read the tags at once into memory before processing the Opus files. That probably deserves a separate pull request before we can merge this one.

I will look at this next.

> It is also missing test cases in `opustags.t`.

Added.

> Such a feature raises a few other questions:
> 
>     1. What to do when the same file is specified twice? I think it is reasonable to edit it twice. That’s what sed does.

I agree; and this will happen automatically.

>     2. What to do when one file fails? Shouldn’t we continue?

Done!

>     3. What should be the error code if some files succeed but other fail? Right now opustags returns either 0 or 1, so I guess 1 is better when there is a failure.

Done!

2020-09-19 09:43 UTC, fmang requested changes
Not too bad. The Perl test is not useful but I can write one later. Error handling needs to be fixed though.

I think we should merge #30 first, which will simply parse_options a bit.

2020-09-19 09:43 UTC, fmang commented on src/cli.cc
> +			rc = next_rc;
That’s a surprising way to write it, since rc is by convention the return code of the latest operation. Your should rename next_rc to rc, and the global rc to global_rc. Then you can write:

```c++
if (rc != st::ok)
    rc = st::error;
```

You’ll also notice that we can’t return all the errors to the parent, so we either need an aggregate error, or to handle errors ourselves. I’d suggest we go for the latter. The caller (main) just prints the message, so we just have to move the print here to print all the errors and not just the first.

2020-09-19 09:43 UTC, fmang commented on src/cli.cc
> +	for (const std::pair<std::string, std::string>& path_in_out : opt.paths_in_out) {
C++17 has a very cool pair deconstruction syntax, you can give it a try.
https://en.cppreference.com/w/cpp/language/structured_binding

2020-09-19 09:43 UTC, fmang commented on src/cli.cc
> +static ot::status run_single(const ot::options& opt, std::string path_in, std::string path_out)
Take the strings as const&.

2020-09-19 09:43 UTC, fmang commented on src/cli.cc
> +			opt.paths_in_out.emplace_back(std::pair<std::string, std::string>("", optarg));
I thinks that’s too eager. You should store path_out in a dedicated local variable, and later when you’re reading argv for input files you’ll be able to build the right pair. This is gonna be more readable.

2020-09-20 18:17 UTC, rrthomas commented
How is the Perl test not useful?

2020-09-20 18:17 UTC, rrthomas commented on src/cli.cc
> +			rc = next_rc;
Done.

2020-09-20 18:18 UTC, rrthomas commented on src/cli.cc
> +	for (const std::pair<std::string, std::string>& path_in_out : opt.paths_in_out) {
Done.

2020-09-20 18:18 UTC, rrthomas commented on src/cli.cc
> +static ot::status run_single(const ot::options& opt, std::string path_in, std::string path_out)
Done.

2020-09-20 18:19 UTC, rrthomas commented on src/cli.cc
> +			opt.paths_in_out.emplace_back(std::pair<std::string, std::string>("", optarg));
Done.

2020-09-20 18:19 UTC, rrthomas commented
I think I've dealt with all your comments; thanks for the review!

2020-09-21 19:01 UTC, fmang commented
> How is the Perl test not useful?

It doesn’t check that out2.opus was indeed processed. A better test would be to have two files with different tags, perform an incremental operation like --add, then check the content of both files. You can see most other tests check the MD5 because that’s easy. By the way, calling opustags to copy gobble.opus to out.opus is a bit awkward, Perl has *copy* for that. Still about style: no need to unlink out2.opus at the beginning of the file since we’ll overwrite it anyway. If you do want to unlink it, unlink it near where it’s needed.

I think you forgot to push your changes. Please also rebase them on the new master.

2020-09-21 20:57 UTC, rrthomas commented
Sorry, I pushed my changes to a different branch. Now pushed to this branch.

2020-09-21 21:15 UTC, rrthomas commented
I updated the test as suggested.

2020-09-22 17:58 UTC, fmang requested changes
The feature is good overall, except for the weird error handling.

2020-09-22 17:58 UTC, fmang commented on t/opustags.t
> +opustags(qw(gobble.opus -o out.opus));
Try `copy('gobble.opus', 'out.opus')` instead. You may need `use File::Copy;` at the beginning of the file.

2020-09-22 17:58 UTC, fmang commented on src/opustags.h
> +	 * special "-" string means stdin for input and stdout for output.
Why can’t they be empty? Did you mean the vector or the file paths? Either way we shouldn’t make a special constraint for that. An empty vector won’t do anything, which is fine, and an empty file path will raise a file not found error, which is fine too.

2020-09-22 17:58 UTC, fmang commented on src/cli.cc
> +			fprintf(stderr, "error: %s\n", rc.message.c_str());
That thing means all but the first messages will be displayed in order, and then the first message will be printed last. That’s super weird. Don’t bother with the special case and print all the messages here, then remove the print from main. If you need to expose run_single so that tests won’t break, feel free to do so.

Concerning the error message to return, since its only caller will eventually only check if it’s OK or not, you can return a generic failure as I suggested.

2020-09-22 17:58 UTC, fmang commented on src/cli.cc
> +										  path_out ? path_out.value() : ""));
See https://en.cppreference.com/w/cpp/utility/optional/value_or

You’re kinda doing the opposite of not handling empty paths specially, eh? I suggest you make a structure like:

```c++
struct operation {
    std::string path_in;
    std::optional<std::string> path_out;
};
```

Where *operation* would be a new terminology meaning a set of options specific to one file or pair of files. If you have a better name please do use it.

2020-09-22 18:03 UTC, rrthomas commented on t/opustags.t
> +opustags(qw(gobble.opus -o out.opus));
Done.

2020-09-22 18:04 UTC, rrthomas commented on src/opustags.h
> +	 * special "-" string means stdin for input and stdout for output.
They can, the comment is out of date.

2020-09-22 18:14 UTC, rrthomas commented on src/cli.cc
> +			fprintf(stderr, "error: %s\n", rc.message.c_str());
Done. Don't need to expose `run_single`, but do need to print the error message in `main` when parsing fails.

2020-09-22 18:57 UTC, rrthomas commented on src/cli.cc
> +										  path_out ? path_out.value() : ""));
This was getting silly. There are two cases: either there's an unrelated `path_in` and `path_out`, or we're doing in-place operations. Trying to shoe-horn both of these into one data structure is what's causing the problem.

So instead, I've reverted to having a list of paths in, and an optional path out. I've also surfaced the in place flag in the options struct.

Then, run has two simple cases: either in-place, or one call to `run_single`, whose second argument is optional.

Finally, `run_single` prints the error message, if any (avoiding duplication in `run()`), and I've restructured it to have a single exit point, so again it's easier to follow.

2020-09-26 08:32 UTC, fmang requested changes
The error handling is broken, but the rest is perfect.

I appreciate your decision to rollback to paths_in and add an in-place option instead. If you feel like some design is awkward, not sticking to it is usually a good decision :)

2020-09-26 08:32 UTC, fmang commented on src/cli.cc
> +		}
This is broken. You can’t keep only the last rc. Since only ok or not-ok matters for the caller, you may either return one of the bad error codes, or return a generic error code if at least one run_single fails.

Your omission of optional brace for the else is a bit weird, especially since you did write them for the for.

I’m surprised you didn’t print the errors in run, but preferred to add a complexity level (even two) in run_single. How about:

```c++
ot::status global_rc = st::ok;
for (const auto& path_in : opt.paths_in) {
    rc = run_single(opt, path_in, opt.in_place ? std::optional(path_in), opt.path_out);
    if (rc != st::ok) {
        global_rc = st::error;
        if (!rc.message.empty())
            printf…
    }
}
```

2020-09-26 09:47 UTC, rrthomas commented on src/cli.cc
> +		}
One man's added complexity is another's simplicity! Thanks for the review; you seem to have this one under control, so I'll let you finish it off, and I look forward to the results.

2020-09-26 10:37 UTC, rrthomas commented
Many thanks! And thanks once again for writing opustags…I must file a bug to ask for it to be packaged in Debian!

2020-09-26 11:12 UTC, merged

2020-09-26 11:14 UTC, fmang commented
Merci à vous !