With --set-all, read comments from stdin before processing tags
fmang/opustags pull request #29
Opened 2020-08-23 21:15 UTC by rrthomas

2020-08-24 17:56 UTC, fmang commented
Maybe we could do more elegant than that. At first I considered deleting `options::set_all` because it is equivalent to a combination of `options::delete_all` and `options::to_add`. However, I didn’t like that parse_options read stdin, in particular because it makes it harder to test.

An alternative would be for `run` to convert set_all to delete_all+to_add after reading stdin, but `run` shouldn’t edit its options, so this doesn’t sound like good design. The current design where `process` reads stdin late is not good either by the way.

I think the best option is to add a FILE* parameter to parse_options for it to populate `to_add`. The main function will pass stdin, but the test suite can give it an *fmemopen* handle. parse_options will have to keep a local `set_all` boolean to check for arguments consistency before actually consuming its input at the end.

What do you think?

2020-08-28 22:17 UTC, rrthomas commented
Your design sounds OK to me. I've implemented it; take a look!

2020-08-29 07:48 UTC, fmang requested changes
Nice! You need to move the call to read_comments and merge the read comments with to_add. The rest are details.

2020-08-29 07:48 UTC, fmang commented on src/cli.cc
> +ot::status ot::parse_options(int argc, char** argv, ot::options& opt, FILE* comments)
Maybe rename it `comments_input`?

2020-08-29 07:48 UTC, fmang commented on src/cli.cc
> +			}
`read_comments` should be called as late as possible, so that the early return for opt.print_help takes precedence. All the other parameter validations should be run before we start performing I/O too.

With the current implementation, `-a A=x -S -a B=y` would read the comment from stdin, then append A=x and B=y at the end. I think we should preserve that behavior instead of clearing `to_add`.

2020-08-29 07:48 UTC, fmang commented on src/opustags.h
> +status read_comments(FILE* input, std::vector<std::string>& comments);
Maybe make it clear in the documentation above that the read comments are appended to `comments`.

2020-08-29 07:48 UTC, fmang commented on src/opustags.h
> -	bool set_all = false;
Mention that --set-all affects delete_all and to_add.

2020-08-29 07:48 UTC, fmang commented on t/cli.cc
> +		FILE *input = fmemopen(NULL, 0, "r");
Use `ot::file` instead. It behaves like a FILE* but fcloses it automatically. You might need to call .get() to get the old FILE*. Same thing below.

Also, give it some data to feed on to improve the test coverage. Something trivial like `"N=1\n"` will do, because we don’t need to test read_comments itself, just make sure parse_options calls it.

2020-08-29 07:48 UTC, fmang commented on t/cli.cc
> +		ot::status rc = parse_options(args, opt, input);
Same as above. Plus, the input is practically never read even with -S because parse_options will return early, so you can add invalid data like `"INVALID"`. Add an extra error case to trigger it and that will be perfect.

2020-08-30 19:30 UTC, rrthomas commented
I think I've addressed all your latest comments; thanks for making them so detailed and easy to digest. Note that the comments read with `read_comments` are *pre*pended to `to_add`, so that as you say in your example the final result is to "append A=x and B=y at the end".

2020-08-31 19:13 UTC, fmang requested changes
We’re getting there! Beware the algorithmic complexity of your code.

2020-08-31 19:13 UTC, fmang commented on src/cli.cc
> +			ncomments++;
This implementation is terribly inefficient because inserting elements in the middle of a vector is very slow. You should revert to the previous emplace_back and let the caller concatenate the read comments with to_add, like that:

```c++
std::vector<std::string> comments;
// read_comments into comments, with error checking
comments.reserve(comments.size() + to_add.size());
std::move(to_add.begin(), to_add.end(), std::back_inserter(comments));
to_add = std::move(comments);
```

Feel free to ask questions if you’re not sure how it is better.

2020-08-31 19:26 UTC, rrthomas commented on src/cli.cc
> +			ncomments++;
I don't know much C++ and I am being lazy on this project. The efficiency doesn't matter in this case (lists of tags are "short"), but the code is nicer your way as `read_comments` doesn't need to cope with existing contents of `comments`.

2020-08-31 19:26 UTC, rrthomas commented
I think I've addressed your latest round of comments.

2020-08-31 19:42 UTC, fmang commented
I beg to differ. Many micro-optimizations don’t matter much, but
algorithmic complexity is a real thing. With your implementation,
specifying `-a` n times makes the operation n times as slow. 10 `-a` in
a row is enough to make your code *an order of magnitude* slower.

2020-08-31 19:45 UTC, fmang commented
I’ll check your new code tomorrow.

2020-08-31 19:50 UTC, rrthomas commented
> (replying to your comment about performance) I beg to differ. Many micro-optimizations don’t matter much, but algorithmic complexity is a real thing. With your implementation, specifying `-a` n times makes the operation n times as slow. 10 `-a` in a row is enough to make your code *an order of magnitude* slower.

I guarantee you no user would ever care, as no user would ever notice. Trust me, I've been strenuously avoiding unnecessary optimizations for 20 years now!

2020-09-19 09:02 UTC, merged

2020-09-19 09:11 UTC, rrthomas commented
Great stuff! I'll continue with my other changes.

2020-09-19 09:15 UTC, fmang commented
About the performance debate, I’m not talking about complex optimization to save a few nanoseconds, but taking a minute to reflect upon the better algorithm before writing code. Prepending or appending take about the same time to code, but have a tremendous impact on performance.

I agree with you that most of the time micro-optimizations aren’t worth spending time on them, but learning to optimize is a good way to grab the much better option when it’s within arm’s reach.

2020-09-20 11:55 UTC, rrthomas commented
> Prepending or appending take about the same time to code, but have a tremendous impact on performance.

Not in this case: the difference is between a constant-time and linear operation (hence linear or quadratic performance) over perhaps a dozen items at most.

> I agree with you that most of the time micro-optimizations aren’t worth spending time on them, but learning to optimize is a good way to grab the much better option when it’s within arm’s reach.

No point wasting brain cycles on that when correctness and clarity are much more important, as here.

I do agree, though, that in this case we were able to get both better performance and clearer code. The point I was trying to make is that only clearer code mattered in this case.