Don't treat empty output filename specially (fix #27)
fmang/opustags pull request #30
Opened 2020-08-31 19:03 UTC by rrthomas

2020-08-31 19:22 UTC, fmang requested changes
You’re breaking this code in ot::run:

```c++
	/* Read-only mode. */
	if (opt.path_out.empty())
		return process(reader, nullptr, opt);
```

If someone specified `-o ""` then this code will just treat it as if -o wasn’t specified at all.

I’ll upgrade the build system to use C++17, so you’ll be able to use `std::optional` instead of keeping a boolean.

2020-08-31 19:24 UTC, rrthomas commented
I've already pushed a PR that rewrites the code that was broken; but I agree that an `optional` would be better.

2020-09-19 09:18 UTC, fmang commented
You should now be able to use std::optional: 5ea2db2d6d57315c99922684a67005fbcc62fc3d

2020-09-20 11:52 UTC, rrthomas commented
I've updated the branch to use `std::optional`.

2020-09-20 13:42 UTC, fmang commented
Pretty cool! Why bother with all the casts though? If I’m not mistaken:

1. x = std::optional(y) could be written x = y.
2. x.value() == y could be written x == y.
3. x.value().c_str() could be written x->c_str().

2020-09-20 14:17 UTC, rrthomas commented
Because I don't know much C++! PR updated.

2020-09-20 14:32 UTC, fmang commented on t/cli.cc
> +	           "Cannot specify --output more than once.", "double output with first filename empty");
Very nice edge case!

2020-09-20 14:32 UTC, merged

2020-09-20 14:33 UTC, fmang commented
Thanks!